name: "Terraform validate"
description: "Validate terraform files"
inputs:
  token:
    description: "GitHub token"
    required: true
  branch:
    description: "Branch to validate"
    required: true
  tf_dir:
    description: "Terraform directory"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - uses: "actions/checkout@v3"
      name: "Checkout"
      with:
        token: ${{ inputs.token }}
        ref: ${{ inputs.branch }}
    - name: "Setup terraform"
      uses: "hashicorp/setup-terraform@v1"
    - name: Run terraform validate
      working-directory: ${{ inputs.tf_dir }}
      run: terraform validate
