name: test custom action
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    name: call action
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: false
      - name: get content
        id: getcontent
        run: |
          echo 'content<<EOF' >> $GITHUB_OUTPUT
          cat README.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: call
        uses: tomasstorc/markdowntest@main
        with:
          #  markdown: ${{ steps.getcontent.outputs.content }}
          filename: README.md
        env:
          CNFL_URL: https://tstest-dev.atlassian.net/
          SPACE_KEY: ~701219c9808ed6f6b4abda4f307a0e1ab58a6
          CNFL_USER: ${{ secrets.CNFL_USER }}
          API_KEY: ${{ secrets.API_KEY }}
