name: test custom action
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    name: call action
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: false
      - name: get content
        id: getcontent
        run: |
          text=$(cat README.md)
          echo "content=$text" >> $GITHUB_OUTPUT
          cat README.md
      - name: call
        uses: tomasstorc/markdowntest@main
        with:
          markdown: ${{ steps.getcontent.outputs.content }}
